### PR TITLE
Adds `Most Liked` widget to P2 Likes

### PR DESCRIPTION
**Pull request by davisshaver**
See https://github.com/scottbasgaard/p2-likes/issues/2

Widget settings:
- Number of items to show
- Number of days to consider (0 for all time)
- Include comments

screen shot 2015-11-16 at 2 08 46 pm

Slight differentiation on comments, otherwise all post formats treated same for now. In my testing, I felt like using the actual "title" was better than `p2_the_title()` as advised here bc `p2_the_title()` ends up empty string for statuses and quotes, and it's not clear to me that using an `excerpt` would be better. 

screen shot 2015-11-16 at 2 09 49 pm

One idea I had was using icons to indicate format type, but I wasn't sure this needed to be in the MVP.

### CODE REVIEW

**Comment by davisshaver** [comment]
@scottbasgaard I'd be interested in your code review of this PR.

**Comment by davisshaver** [comment]
Testing in multisite revealed some `wpdb` issues. Looking into fix.

**Comment by scottbasgaard** [comment]
Nice work man!

I'll get to merging this / deploying this week.

Some small formatting & code standards I wanna get fixed but other than that it looks good :+1:

**Comment by davisshaver** [comment]
Sweet, thanks @scottbasgaard. Lemme know if you see anything to help with.

**Comment by davisshaver** [comment]
@scottbasgaard anything I can do to push this along? You can also leave comments for me if that's easier.

**Comment by scottbasgaard** [comment]
@davisshaver hey bud, just merged this in and deploying to .org now.

Sorry for the delay, been on vacation visiting my family in the 🇺🇸 and just getting on my computer now after being mobile for almost a week.

Great work here and thanks again man.

**Comment by davisshaver** [comment]
Cool! Glad to help out... and hope you had a great vacation :earth_americas:. Thanks for merging.

**Pull request merged**
